# Series Basics

In this section, we build on what we learned about sequences to talk about one of their most important use cases: series. Loosely speaking, we think of a series as an "infinite sum", and one of the primary questions we seek to address is when a series converges to a finite number and when it doesn't. Consider for example, the four infinite sums below:

$$\begin{array}{l}
1+2+3+4+\cdots \\~\\
1+(-1)+1+(-1)+\cdots \\~\\
1+\frac{1}{2}+\frac{1}{3}+\frac{1}{4}+\cdots \\~\\
%1+\left(-\frac{1}{2}\right)+\frac{1}{4}+\left(-\frac{1}{8}\right)+\cdots
1+\frac{1}{2}+\frac{1}{4}+\frac{1}{8}+\frac{1}{16}+\cdots
\end{array}$${#eq-first-examples}

Some of these might strike you as obviously undefined or obviously convergent, but others may not. In what follows below, we'll make a precise definition of what we mean by convergent so that we can prove theorems and talk coherently about examples.^[There are actually several theories of convergent series which are useful in different contexts. We'll present the most standard version here.]

## Series and Partial Sums

Suppose $(a_n)$ is a sequence in $\mathbb{R}$. Then the *series* with terms $(a_n)$ is the formal expression

$$\sum_{i=1}^\infty a_i=a_1+a_2+\cdots$$

By "formal expression" I mean that we are not considering this expression to represent a number; it's just notation meant to express the *idea* of an infinite sum. Sometimes we abbreviate the notation as $\sum a_i$.

::: {.definition #def-partial-sum}

## Partial Sums

The *sequence of partial sums* of the series $\displaystyle\sum_{i=1}^\infty a_i$ is the sequence $(s_n)$ defined by
$$ s_n=\sum_{i=1}^n a_i = a_1+\cdots+a_n $$
:::

This means that
$$\begin{array}{ccl}
s_1&=&a_1\\
s_2&=&a_1+a_2\\
s_3&=&a_1+a+2+a_3\\
&\vdots&
\end{array}$$

We now define convergence of series in terms of the partial sums.

::: {.definition #def-series-convergence}

## Series Convergence

The series $\displaystyle\sum_{i=1}^\infty a_i$ is said to *converge* or *diverge* when its sequence of partial sums $(s_n)$ does. If $s_n\rightarrow S$, we call $S$ the *sum* of the series.
:::

In the case that $\displaystyle\sum_{i=1}^\infty a_i$ has sum $S$, we sometimes abuse notation slightly and use the expression $\displaystyle\sum_{i=1}^\infty a_i$ to represent the number $S$.

As an example of the vocabulary in the action, the series $\displaystyle \sum_{i=1}^\infty \frac{2}{3^i}$

- has *terms* given by the sequence $\left(\frac{2}{3^i}\right)$ or $\frac{2}{3},\frac{2}{9},\frac{2}{27},\frac{2}{81},\cdots$
- has *partial sums* $\frac{2}{3},\frac{2}{3}+\frac{2}{9},\frac{2}{3}+\frac{2}{9}+\frac{2}{27},\ldots$. These simplifies to $\frac{2}{3},\frac{8}{9},\frac{26}{27},\ldots$ or $\left(\frac{3^i-1}{3^i}\right)$.
- *converges* with a *sum* of $1$.

::: {.exercise #exr-partial-sum-practice}
Write each of the four infinite sums in [@eq-first-examples] using series notation. Then write out the first 6 partial sums for each. Are there any you can tell right away converge or diverge?
:::

## Working with Partial Sums

We start with an important class of series called *geometric series*.

::: {.example #exm-geometric}

## Geometric Series

For $a\neq 0$ and any $r\in\mathbb{R}$, a series of the form
$$\sum_{i=0}^\infty ar^n$$
is called a *geometric series*. This series converges to $\frac{a}{1-r}$ when $|r|<1$ and diverges otherwise.
:::

:::{.proof}
To determine whether the series converges, we analyze its partial sums in cases.
  
If $|r|\neq1$, we can use some algebraic tricks to simplify the expression for the partial sum $s_n$:
$$\begin{array}{rcl}
  s_n&=&a+ar+ar^2+cdots+ar^n\\
  &=&a(1+r+r^2+\cdots+r^n)\\
  &=&\displaystyle\frac{a(1-r^{n+1})}{1-r}
\end{array}$$
If $|r|<1$, then $r^{n+1}\rightarrow0$, so using what we know about sequences and arithmetic, we can say $s_n\rightarrow\frac{a}{1-r}$.

If $|r|>1$, then $(r^{n+1})$ diverges. So if, by way of contradiction, we assume the partial sums $(s_n)$ did converge to some value $S$, then we could say that the sequence $\left(1-s_n\frac{1-r}{a}\right)$ converges to $1-L\frac{1-r}{a}$. However $1-s_n\frac{1-r}{a}=r^{n+1}$, which we already said diverges.^[I am bending over backwards here to make precise the intuition that "Since $(r^{n+1})$ diverges, so must an sequence involving it". Unfortunately, that reasoning doesn't always work--think about $(\sqrt{n+1} - \sqrt{n})$ which converges despite being the sum of two divergent sequences--so a proof of the style shown here is appropriate.]

We leave the cases where $r=\pm1$ to the reader in @exr-geometric-with-r-pm1 below.
:::

::: {.exercise #exr-geometric-with-r-pm1}
Finish the proof of @exm-geometric by proving that the geometric series diverges when $r=1$ and when $r=-1$. (Hint: what are the partial sums in each of these cases?)
:::

:::{.callout-note}
In the section on sequences, we insisted that the first term in our sequence corresponded to an index of 1. For series, it is often convenient to start with an index 0 (as in @exm-geometric) or something else. And now that we are more comfortable with the concept of a sequence, there is less risk of confusion.
:::

::: {.exercise #exr-telescoping-example}

## A "Telescoping" Series

Show that the series $\displaystyle\sum_{i=1}^\infty \frac{1}{n(n+1)}$ converges. It will be helfpul to note that 
$$\frac{1}{n(n+1)}=\frac{1}{n}-\frac{1}{n+1}$$
and to write out the first several partial sums.
:::

Both @exm-geometric and @exr-telescoping-example are somewhat unusual in that in both cases we can write down an explicit formula for the partial sum sequence. More often an explicit formula is unavailable and we need to rely on other means for determining and proving the con/divergence of a series.

::: {.theorem #thm-divergence-test}

## Divergence Test

If a series converges, then its terms converge to $0$.

:::

::: {.exercise #exr-divergence-test-proof}
1. State the contrapositive of the Divergence Test.
2. What (if anything) does the Divergence Test say about the con/divergence of the series $\displaystyle \sum_{i=1}^\infty \frac{n}{n+1}$?.
3. What (if anything) does the Divergence Test say about the con/divergence series $\displaystyle \sum_{i=1}^\infty \frac{1}{n^2}$?
4. Prove the Divergence Test.
:::

:::{.callout-tip collapse="true"}
## Hint for part 4 of @exr-divergence-test-proof

Note that $a_{n+1}=s_{n+1}-s_n$.
:::


::: {.theorem #thm-series-order-arithmetic}
Suppose $\sum a_n=S$ and $\sum b_n=T$ are convergent series and that $k\in\mathbb{R}$. Then

1. $\sum (a_n+b_n) = S+T$
2. $\sum (ka_n)=kS$
3. If $a_n\leq b_n$ for all $n$, then $S\leq T$.
:::

Part of what parts 1 and 2 in @thm-series-order-arithmetic is claiming is that these two series do in fact converge.

:::{.callout-note}
When an equation or proposition does not depend on the starting index of a series, we sometimes just write $\sum a_n$ as shorthand for $\sum_{i=k}^\infty a_n$ for some $k$.
:::

## Series With Non-Negative Terms

Series with all non-negative terms have some special properties that we can quickly prove using what we know about sequences.

::: {.exercise #exr-positive-terms}
Suppose $\displaystyle \sum_{i=1}^\infty a_i$ is a series all of whose terms are non-negative. Prove the following.

1. The sequence of partial sums is increasing.
2. The series converges if and only if the sequence of partial sums is bounded.
3. If the series diverges, then the sequence of partial sums limits to $+\infty$.
:::

The upshot of @exr-positive-terms is that we can determine the con/divergence of a series just by knowing whether its sequence of partial sums is bounded or not. This can be very helpful for proving 

::: {.example #exm-basel-series}
The series $\displaystyle\sum_{i=1}^\infty \frac{1}{n^2}$ converges.
:::

:::{.proof}
Let $(s_n)$ be the sequence of partials sums for $\displaystyle\sum_{i=1}^\infty \frac{1}{n^2}$.

As we say in @exr-telescoping-example, the series $\displaystyle\sum_{i=1}^\infty \frac{1}{n(n+1)}$ converges. Let $(t_n)$ be the sequence of partial sums for this series.

Comparing the partials sums for these two series, we have
$$\begin{array}{ccccccc}
s_n&=&1+&\frac{1}{2\cdot2}+&\frac{1}{3\cdot3}+&\cdots&+\frac{1}{n^2}\\
t_n&=&&\frac{1}{1\cdot2}+&\frac{1}{2\cdot3}+&\cdots&+\frac{1}{n(n+1)}
\end{array}$$

Comparing term by term, we can see that $1+t_n\geq s_n$ for all $n$. Since $(t_n)$ has all positive terms and converges to some number $T$, we can use part 2 of @exr-positive-terms to say that that $(t_n)$ and therefore $(s_n)$ is bounded above. Thus, applying part 2 of @exr-positive-terms again, we can say that $\displaystyle\sum_{i=1}^\infty \frac{1}{n^2}$ converges.
:::

Note that the above proof does not tell us what the series $\displaystyle\sum_{i=1}^\infty \frac{1}{n^2}$ converges *to*. This is often the case for such proofs.

The following theorem extends generalizes the logic of the proof of @exm-basel-series.

::: {.theorem #thm-comparison-test}

## Comparison Test

Suppose $\sum a_n$ and $\sum b_n$ are series with all non-negative terms such that $a_n\leq b_n$ for all $n$.

1. If $\sum b_n$ converges, then $\sum a_n$ converges.
2. If $\sum a_n$ diverges, then $\sum b_n$ diverges.

:::

::: {.example #exm-harmonic-series}

## Harmonic Series

The *harmonic series* $\displaystyle \sum_{i=1}^\infty \frac{1}{n}$ diverges.
:::

::: {.proof}
Call the terms of this series $c_n=\frac{1}{n}$ and the partial sums $s_n$. Note that $c_n\rightarrow0$, so the Divergence Test cannot be used to prove divergence.

Consider another series $\displaystyle \sum_{i=1}^\infty b_n$ where the terms $b_n$ are defined by
$$\begin{array}{rcl}
  b_1&=&1\\
  b_2&=&\frac{1}{2}\\
  b_3=b_4&=&\frac{1}{4}\\
  b_5=\cdots=b_8&=&\frac{1}{8}\\
  &\vdots&\\
  b_{2^{n-1}+1}=\cdots=b_{2^n} & = & \frac{1}{2^n}\\
  &\vdots&
\end{array}$$

Note consider the series $\displaystyle \sum_{i=1}^\infty b_n$. Calling the partial sums $t_n$, we can consider the subsequence $t_{2^n}$:
$$\begin{array}{rcll}
  t_{2^1} &=& 1+\frac{1}{2}&=\frac{3}{2}\\
  t_{2^2-1} &=& 1+\frac{1}{2}+2\cdot\frac{1}{4}&=\frac{4}{2}\\
  t_{2^2-1} &=& 1+\frac{1}{2}+2\cdot\frac{1}{4}+4\cdot\frac{1}{8}&=\frac{5}{2}\\
  &\vdots&
\end{array}$$
Thus $t_{2^n}=\frac{n+2}{2}$, so $(t_n)$ has a divergent subsequence and hence $\displaystyle \sum_{i=1}^\infty b_n$ diverges. Therefore since $c_n\geq b_n$ for all $n$ (and both series have all non-negative terms) $\displaystyle \sum_{i=1}^\infty \frac{1}{n}$  diverges as well by the Comparison Test.
:::

::: {.exercise #exr-comp-test-apply}
Prove @thm-comparison-test.
:::
